<a href="https://colab.research.google.com/github/GJ-007-sage/deep-learning/blob/main/Assignment_24b1809_GJ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import re

In [ ]:
text = "The universe is governed by physical laws that can be understood and described mathematically. These laws allow us to explain the phenomena we observe and predict future events. From the smallest particles to the vast expanse of galaxies, the universe operates under principles that reveal its fundamental nature.One of the most profound discoveries in modern physics is the concept of black holes. Black holes are regions of spacetime where gravity is so strong that nothing, not even light, can escape from them. They challenge our understanding of time and space, leading to questions about the very fabric of reality. Understanding black holes and their role in the cosmos could provide insights into the origins of the universe and the laws that govern it. Source: https://www.fisica.net/relatividade/stephen_hawking_a_brief_history_of_time.pdf"

In [ ]:
lowercased_text = text.lower()

lowercased_text

'the universe is governed by physical laws that can be understood and described mathematically. these laws allow us to explain the phenomena we observe and predict future events. from the smallest particles to the vast expanse of galaxies, the universe operates under principles that reveal its fundamental nature.one of the most profound discoveries in modern physics is the concept of black holes. black holes are regions of spacetime where gravity is so strong that nothing, not even light, can escape from them. they challenge our understanding of time and space, leading to questions about the very fabric of reality. understanding black holes and their role in the cosmos could provide insights into the origins of the universe and the laws that govern it. source: https://www.fisica.net/relatividade/stephen_hawking_a_brief_history_of_time.pdf'

In [ ]:
punctuation_pattern = r'[^\w\s]'
text_cleaned = re.sub(punctuation_pattern, '', text)
text_cleaned

'The universe is governed by physical laws that can be understood and described mathematically These laws allow us to explain the phenomena we observe and predict future events From the smallest particles to the vast expanse of galaxies the universe operates under principles that reveal its fundamental natureOne of the most profound discoveries in modern physics is the concept of black holes Black holes are regions of spacetime where gravity is so strong that nothing not even light can escape from them They challenge our understanding of time and space leading to questions about the very fabric of reality Understanding black holes and their role in the cosmos could provide insights into the origins of the universe and the laws that govern it Source httpswwwfisicanetrelatividadestephen_hawking_a_brief_history_of_timepdf'

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
stop_words = set(stopwords.words('english'))

In [ ]:
print(stop_words)

{'up', "wasn't", 'why', 'or', 'into', "mustn't", "shouldn't", 'y', 'me', 'very', 'own', 'd', "you'd", 'of', 'other', 'ain', 'themselves', 'hasn', 'she', 'mustn', 'between', 'he', 'more', 'herself', 'my', 'over', 'out', 'an', 'each', 'most', 'just', 'above', "didn't", 'nor', 'here', 'through', 'because', 'after', "isn't", 'on', "won't", 'ourselves', 'his', 'can', "should've", 'a', 'there', 'ours', 'isn', 'yourselves', 'who', 'such', 'am', 'had', 'any', "weren't", 'under', 'wouldn', 'whom', 'didn', 'some', 'yours', 'same', 'once', "you'll", "shan't", 'theirs', 'wasn', 'then', 'her', 'should', 'how', 'for', 'you', 'is', 'in', 'off', "you've", 'to', 'do', 'shan', 'now', 'your', 'doing', 'few', "it's", "don't", "haven't", 'they', 'was', 'what', 'll', 'when', 'himself', "couldn't", 'been', 'we', 'mightn', 't', 'them', 'couldn', "hadn't", 'if', 'while', 'below', 'will', 'its', 'o', 's', 'as', 'doesn', "doesn't", 'with', 'ma', 'be', 'm', "she's", 'are', 'both', 'no', "mightn't", 'further', 'di

In [ ]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize,sent_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
tokenize_words = word_tokenize(text)

In [ ]:
print(tokenize_words)

['The', 'universe', 'is', 'governed', 'by', 'physical', 'laws', 'that', 'can', 'be', 'understood', 'and', 'described', 'mathematically', '.', 'These', 'laws', 'allow', 'us', 'to', 'explain', 'the', 'phenomena', 'we', 'observe', 'and', 'predict', 'future', 'events', '.', 'From', 'the', 'smallest', 'particles', 'to', 'the', 'vast', 'expanse', 'of', 'galaxies', ',', 'the', 'universe', 'operates', 'under', 'principles', 'that', 'reveal', 'its', 'fundamental', 'nature.One', 'of', 'the', 'most', 'profound', 'discoveries', 'in', 'modern', 'physics', 'is', 'the', 'concept', 'of', 'black', 'holes', '.', 'Black', 'holes', 'are', 'regions', 'of', 'spacetime', 'where', 'gravity', 'is', 'so', 'strong', 'that', 'nothing', ',', 'not', 'even', 'light', ',', 'can', 'escape', 'from', 'them', '.', 'They', 'challenge', 'our', 'understanding', 'of', 'time', 'and', 'space', ',', 'leading', 'to', 'questions', 'about', 'the', 'very', 'fabric', 'of', 'reality', '.', 'Understanding', 'black', 'holes', 'and', 't

In [ ]:
word_tokens = text.split()
word_tokens

['The',
 'universe',
 'is',
 'governed',
 'by',
 'physical',
 'laws',
 'that',
 'can',
 'be',
 'understood',
 'and',
 'described',
 'mathematically.',
 'These',
 'laws',
 'allow',
 'us',
 'to',
 'explain',
 'the',
 'phenomena',
 'we',
 'observe',
 'and',
 'predict',
 'future',
 'events.',
 'From',
 'the',
 'smallest',
 'particles',
 'to',
 'the',
 'vast',
 'expanse',
 'of',
 'galaxies,',
 'the',
 'universe',
 'operates',
 'under',
 'principles',
 'that',
 'reveal',
 'its',
 'fundamental',
 'nature.One',
 'of',
 'the',
 'most',
 'profound',
 'discoveries',
 'in',
 'modern',
 'physics',
 'is',
 'the',
 'concept',
 'of',
 'black',
 'holes.',
 'Black',
 'holes',
 'are',
 'regions',
 'of',
 'spacetime',
 'where',
 'gravity',
 'is',
 'so',
 'strong',
 'that',
 'nothing,',
 'not',
 'even',
 'light,',
 'can',
 'escape',
 'from',
 'them.',
 'They',
 'challenge',
 'our',
 'understanding',
 'of',
 'time',
 'and',
 'space,',
 'leading',
 'to',
 'questions',
 'about',
 'the',
 'very',
 'fabric',
 '

In [ ]:
filtered_text = [word for word in word_tokens if word not in stop_words]
print("Filtered Text:", filtered_text)

Filtered Text: ['The', 'universe', 'governed', 'physical', 'laws', 'understood', 'described', 'mathematically.', 'These', 'laws', 'allow', 'us', 'explain', 'phenomena', 'observe', 'predict', 'future', 'events.', 'From', 'smallest', 'particles', 'vast', 'expanse', 'galaxies,', 'universe', 'operates', 'principles', 'reveal', 'fundamental', 'nature.One', 'profound', 'discoveries', 'modern', 'physics', 'concept', 'black', 'holes.', 'Black', 'holes', 'regions', 'spacetime', 'gravity', 'strong', 'nothing,', 'even', 'light,', 'escape', 'them.', 'They', 'challenge', 'understanding', 'time', 'space,', 'leading', 'questions', 'fabric', 'reality.', 'Understanding', 'black', 'holes', 'role', 'cosmos', 'could', 'provide', 'insights', 'origins', 'universe', 'laws', 'govern', 'it.', 'Source:', 'https://www.fisica.net/relatividade/stephen_hawking_a_brief_history_of_time.pdf']


In [ ]:
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

In [ ]:
remove_urls(text)

'The universe is governed by physical laws that can be understood and described mathematically. These laws allow us to explain the phenomena we observe and predict future events. From the smallest particles to the vast expanse of galaxies, the universe operates under principles that reveal its fundamental nature.One of the most profound discoveries in modern physics is the concept of black holes. Black holes are regions of spacetime where gravity is so strong that nothing, not even light, can escape from them. They challenge our understanding of time and space, leading to questions about the very fabric of reality. Understanding black holes and their role in the cosmos could provide insights into the origins of the universe and the laws that govern it. Source: '

In [ ]:
text2 = """
<h1>Myself an enthusiastic coder</h1>
<p>The bootcamp is fun</p>
<a href="https://example.com"></a>
"""

In [ ]:
html_tags_pattern = r'<.*?>'
text_without_html_tags = re.sub(html_tags_pattern, '', text2)
text_without_html_tags

'\nMyself an enthusiastic coder\nThe bootcamp is fun\n\n'

In [ ]:
from nltk.stem.porter import PorterStemmer

In [ ]:
stemmer = PorterStemmer()

In [ ]:
def stem_words(text):
    word_tokens = text.split()
    stems = [stemmer.stem(word) for word in word_tokens]
    return stems

In [ ]:
stem_words(text)

['the',
 'univers',
 'is',
 'govern',
 'by',
 'physic',
 'law',
 'that',
 'can',
 'be',
 'understood',
 'and',
 'describ',
 'mathematically.',
 'these',
 'law',
 'allow',
 'us',
 'to',
 'explain',
 'the',
 'phenomena',
 'we',
 'observ',
 'and',
 'predict',
 'futur',
 'events.',
 'from',
 'the',
 'smallest',
 'particl',
 'to',
 'the',
 'vast',
 'expans',
 'of',
 'galaxies,',
 'the',
 'univers',
 'oper',
 'under',
 'principl',
 'that',
 'reveal',
 'it',
 'fundament',
 'nature.on',
 'of',
 'the',
 'most',
 'profound',
 'discoveri',
 'in',
 'modern',
 'physic',
 'is',
 'the',
 'concept',
 'of',
 'black',
 'holes.',
 'black',
 'hole',
 'are',
 'region',
 'of',
 'spacetim',
 'where',
 'graviti',
 'is',
 'so',
 'strong',
 'that',
 'nothing,',
 'not',
 'even',
 'light,',
 'can',
 'escap',
 'from',
 'them.',
 'they',
 'challeng',
 'our',
 'understand',
 'of',
 'time',
 'and',
 'space,',
 'lead',
 'to',
 'question',
 'about',
 'the',
 'veri',
 'fabric',
 'of',
 'reality.',
 'understand',
 'black

In [ ]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
lemmatizer = WordNetLemmatizer()

In [ ]:
def lemmatize_word(text):
    word_tokens = text.split()
    lemmas = [lemmatizer.lemmatize(word, pos ='v') for word in word_tokens]
    return lemmas

In [ ]:
lemmatize_word(text)

['The',
 'universe',
 'be',
 'govern',
 'by',
 'physical',
 'laws',
 'that',
 'can',
 'be',
 'understand',
 'and',
 'describe',
 'mathematically.',
 'These',
 'laws',
 'allow',
 'us',
 'to',
 'explain',
 'the',
 'phenomena',
 'we',
 'observe',
 'and',
 'predict',
 'future',
 'events.',
 'From',
 'the',
 'smallest',
 'particles',
 'to',
 'the',
 'vast',
 'expanse',
 'of',
 'galaxies,',
 'the',
 'universe',
 'operate',
 'under',
 'principles',
 'that',
 'reveal',
 'its',
 'fundamental',
 'nature.One',
 'of',
 'the',
 'most',
 'profound',
 'discoveries',
 'in',
 'modern',
 'physics',
 'be',
 'the',
 'concept',
 'of',
 'black',
 'holes.',
 'Black',
 'hole',
 'be',
 'regions',
 'of',
 'spacetime',
 'where',
 'gravity',
 'be',
 'so',
 'strong',
 'that',
 'nothing,',
 'not',
 'even',
 'light,',
 'can',
 'escape',
 'from',
 'them.',
 'They',
 'challenge',
 'our',
 'understand',
 'of',
 'time',
 'and',
 'space,',
 'lead',
 'to',
 'question',
 'about',
 'the',
 'very',
 'fabric',
 'of',
 'realit

In [ ]:
tokens = word_tokenize(text)
print(tokens)

['The', 'universe', 'is', 'governed', 'by', 'physical', 'laws', 'that', 'can', 'be', 'understood', 'and', 'described', 'mathematically', '.', 'These', 'laws', 'allow', 'us', 'to', 'explain', 'the', 'phenomena', 'we', 'observe', 'and', 'predict', 'future', 'events', '.', 'From', 'the', 'smallest', 'particles', 'to', 'the', 'vast', 'expanse', 'of', 'galaxies', ',', 'the', 'universe', 'operates', 'under', 'principles', 'that', 'reveal', 'its', 'fundamental', 'nature.One', 'of', 'the', 'most', 'profound', 'discoveries', 'in', 'modern', 'physics', 'is', 'the', 'concept', 'of', 'black', 'holes', '.', 'Black', 'holes', 'are', 'regions', 'of', 'spacetime', 'where', 'gravity', 'is', 'so', 'strong', 'that', 'nothing', ',', 'not', 'even', 'light', ',', 'can', 'escape', 'from', 'them', '.', 'They', 'challenge', 'our', 'understanding', 'of', 'time', 'and', 'space', ',', 'leading', 'to', 'questions', 'about', 'the', 'very', 'fabric', 'of', 'reality', '.', 'Understanding', 'black', 'holes', 'and', 't

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(tokens)
feature_names = vectorizer.get_feature_names_out()
X_array = X.toarray()

In [ ]:
print("Unique Word List: \n", feature_names)
print("Bag of Words Matrix: \n", X_array)

Unique Word List: 
 ['about' 'allow' 'and' 'are' 'be' 'black' 'by' 'can' 'challenge' 'concept'
 'cosmos' 'could' 'described' 'discoveries' 'escape' 'even' 'events'
 'expanse' 'explain' 'fabric' 'fisica' 'from' 'fundamental' 'future'
 'galaxies' 'govern' 'governed' 'gravity' 'holes' 'https' 'in' 'insights'
 'into' 'is' 'it' 'its' 'laws' 'leading' 'light' 'mathematically' 'modern'
 'most' 'nature' 'net' 'not' 'nothing' 'observe' 'of' 'one' 'operates'
 'origins' 'our' 'particles' 'pdf' 'phenomena' 'physical' 'physics'
 'predict' 'principles' 'profound' 'provide' 'questions' 'reality'
 'regions' 'relatividade' 'reveal' 'role' 'smallest' 'so' 'source' 'space'
 'spacetime' 'stephen_hawking_a_brief_history_of_time' 'strong' 'that'
 'the' 'their' 'them' 'these' 'they' 'time' 'to' 'under' 'understanding'
 'understood' 'universe' 'us' 'vast' 'very' 'we' 'where' 'www']
Bag of Words Matrix: 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(data=X_array, columns=feature_names, index=tokens)
(df)

about  allow  and  are  \
The                                                     0      0    0    0   
universe                                                0      0    0    0   
is                                                      0      0    0    0   
governed                                                0      0    0    0   
by                                                      0      0    0    0   
...                                                   ...    ...  ...  ...   
Source                                                  0      0    0    0   
:                                                       0      0    0    0   
https                                                   0      0    0    0   
:                                                       0      0    0    0   
//www.fisica.net/relatividade/stephen_hawking_a...      0      0    0    0   

                                                    be  black  by  can  \
The                                                  0      0   0    0   
universe                                             0      0   0    0   
is                                                   0      0   0    0   
governed                                             0      0   0    0   
by                                                   0      0   1    0   
...                                                 ..    ...  ..  ...   
Source                                               0      0   0    0   
:                                                    0      0   0    0   
https                                                0      0   0    0   
:                                                    0      0   0    0   
//www.fisica.net/relatividade/stephen_hawking_a...   0      0   0    0   

                                                    challenge  concept  ...  \
The                                                         0        0  ...   
universe                                                    0        0  ...   
is                                                          0        0  ...   
governed                                                    0        0  ...   
by                                                          0        0  ...   
...                                                       ...      ...  ...   
Source                                                      0        0  ...   
:                                                           0        0  ...   
https                                                       0        0  ...   
:                                                           0        0  ...   
//www.fisica.net/relatividade/stephen_hawking_a...          0        0  ...   

                                                    under  understanding  \
The                                                     0              0   
universe                                                0              0   
is                                                      0              0   
governed                                                0              0   
by                                                      0              0   
...                                                   ...            ...   
Source                                                  0              0   
:                                                       0              0   
https                                                   0              0   
:                                                       0              0   
//www.fisica.net/relatividade/stephen_hawking_a...      0              0   

                                                    understood  universe  us  \
The                                                          0         0   0   
universe                                                     0         1   0   
is                                                           0         0   0   
governed                                    

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(tokens)
terms = tfidf_vectorizer.get_feature_names_out()
df = pd.DataFrame(tfidf_matrix.toarray(), columns=terms)
(df)

about  allow  and  are   be  black   by  can  challenge  concept  ...  \
0      0.0    0.0  0.0  0.0  0.0    0.0  0.0  0.0        0.0      0.0  ...   
1      0.0    0.0  0.0  0.0  0.0    0.0  0.0  0.0        0.0      0.0  ...   
2      0.0    0.0  0.0  0.0  0.0    0.0  0.0  0.0        0.0      0.0  ...   
3      0.0    0.0  0.0  0.0  0.0    0.0  0.0  0.0        0.0      0.0  ...   
4      0.0    0.0  0.0  0.0  0.0    0.0  1.0  0.0        0.0      0.0  ...   
..     ...    ...  ...  ...  ...    ...  ...  ...        ...      ...  ...   
133    0.0    0.0  0.0  0.0  0.0    0.0  0.0  0.0        0.0      0.0  ...   
134    0.0    0.0  0.0  0.0  0.0    0.0  0.0  0.0        0.0      0.0  ...   
135    0.0    0.0  0.0  0.0  0.0    0.0  0.0  0.0        0.0      0.0  ...   
136    0.0    0.0  0.0  0.0  0.0    0.0  0.0  0.0        0.0      0.0  ...   
137    0.0    0.0  0.0  0.0  0.0    0.0  0.0  0.0        0.0      0.0  ...   

     under  understanding  understood  universe   us  vast  very   we  where  \
0      0.0            0.0         0.0       0.0  0.0   0.0   0.0  0.0    0.0   
1      0.0            0.0         0.0       1.0  0.0   0.0   0.0  0.0    0.0   
2      0.0            0.0         0.0       0.0  0.0   0.0   0.0  0.0    0.0   
3      0.0            0.0         0.0       0.0  0.0   0.0   0.0  0.0    0.0   
4      0.0            0.0         0.0       0.0  0.0   0.0   0.0  0.0    0.0   
..     ...            ...         ...       ...  ...   ...   ...  ...    ...   
133    0.0            0.0         0.0       0.0  0.0   0.0   0.0  0.0    0.0   
134    0.0            0.0         0.0       0.0  0.0   0.0   0.0  0.0    0.0   
135    0.0            0.0         0.0       0.0  0.0   0.0   0.0  0.0    0.0   
136    0.0            0.0         0.0       0.0  0.0   0.0   0.0  0.0    0.0   
137    0.0            0.0         0.0       0.0  0.0   0.0   0.0  0.0    0.0   

          www  
0    0.000000  
1    0.000000  
2    0.000000  
3    0.000000  
4    0.000000  
..        ...  
133  0.000000  
134  0.000000  
135  0.000000  
136  0.000000  
137  0.408248  

[138 rows x 92 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
import numpy as np

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
tokenized_text = [nltk.word_tokenize(sentence.lower()) for sentence in text]

In [ ]:
all_words = [word for sentence in tokenized_text for word in sentence]

In [ ]:
vocab = sorted(set(all_words))

In [ ]:
print("Vocabulary:", vocab)

Vocabulary: [',', '.', '/', ':', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y']


In [ ]:
word_array = np.array(all_words).reshape(-1, 1)

In [ ]:
one_hot_encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded = one_hot_encoder.fit_transform(word_array)

In [ ]:
print("One-hot encoded matrix:\n", one_hot_encoded)

One-hot encoded matrix:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
import matplotlib.pyplot as plt

In [ ]:
from gensim.models import Word2Vec