<a href="https://colab.research.google.com/github/GJ-007-sage/deep-learning/blob/main/Copy_of_Assignment_24b1809_GJ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import re

In [ ]:
text = "The universe is governed by physical laws that can be understood and described mathematically. These laws allow us to explain the phenomena we observe and predict future events. From the smallest particles to the vast expanse of galaxies, the universe operates under principles that reveal its fundamental nature.One of the most profound discoveries in modern physics is the concept of black holes. Black holes are regions of spacetime where gravity is so strong that nothing, not even light, can escape from them. They challenge our understanding of time and space, leading to questions about the very fabric of reality. Understanding black holes and their role in the cosmos could provide insights into the origins of the universe and the laws that govern it. Source: https://www.fisica.net/relatividade/stephen_hawking_a_brief_history_of_time.pdf"

In [ ]:
lowercased_text = text.lower()

lowercased_text

'the universe is governed by physical laws that can be understood and described mathematically. these laws allow us to explain the phenomena we observe and predict future events. from the smallest particles to the vast expanse of galaxies, the universe operates under principles that reveal its fundamental nature.one of the most profound discoveries in modern physics is the concept of black holes. black holes are regions of spacetime where gravity is so strong that nothing, not even light, can escape from them. they challenge our understanding of time and space, leading to questions about the very fabric of reality. understanding black holes and their role in the cosmos could provide insights into the origins of the universe and the laws that govern it. source: https://www.fisica.net/relatividade/stephen_hawking_a_brief_history_of_time.pdf'

In [ ]:
punctuation_pattern = r'[^\w\s]'
text_cleaned = re.sub(punctuation_pattern, '', text)
text_cleaned

'The universe is governed by physical laws that can be understood and described mathematically These laws allow us to explain the phenomena we observe and predict future events From the smallest particles to the vast expanse of galaxies the universe operates under principles that reveal its fundamental natureOne of the most profound discoveries in modern physics is the concept of black holes Black holes are regions of spacetime where gravity is so strong that nothing not even light can escape from them They challenge our understanding of time and space leading to questions about the very fabric of reality Understanding black holes and their role in the cosmos could provide insights into the origins of the universe and the laws that govern it Source httpswwwfisicanetrelatividadestephen_hawking_a_brief_history_of_timepdf'

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to C:\Users\Guru Jahnavi
[nltk_data]     Madana\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [ ]:
stop_words = set(stopwords.words('english'))

In [ ]:
print(stop_words)

{'mustn', 'when', 'my', 'each', 'as', 've', 'being', 'were', 'ma', 'having', 'shouldn', 'shan', "didn't", 'we', 'which', 'haven', 'itself', "you'd", 'again', 'isn', 'them', 'then', 'aren', 'all', 'its', 'her', 'from', "haven't", 'him', 'same', 'will', 'has', 'yours', 'wasn', "you've", 'so', 'what', 'off', 'didn', 'into', 'mightn', 'at', 'after', 'hasn', 'there', 'own', 'won', 'few', 'where', "isn't", 'down', 'on', 'once', 'over', 'because', "won't", 'how', 'no', 'until', "mustn't", 'y', 'ain', 'more', 'during', 'against', 'himself', 'their', 'theirs', 'through', 'couldn', 'they', "weren't", "shouldn't", "hadn't", 'but', 'be', 'below', 'just', 'for', 'above', 'your', 'had', 'doing', 'before', 'and', 'most', 'further', 'other', 'needn', 'can', "needn't", 'between', 'any', "don't", 'is', 'you', 'hers', 're', "mightn't", 'm', "it's", 'these', 'up', "you're", 'not', 'should', 'here', 'than', 'nor', 'myself', "that'll", 'been', 'whom', "should've", "you'll", 'in', 'this', 'was', 'doesn', 'he

In [ ]:
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize,sent_tokenize

[nltk_data] Downloading package punkt_tab to C:\Users\Guru Jahnavi
[nltk_data]     Madana\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


In [ ]:
tokenize_words = word_tokenize(text)

In [ ]:
print(tokenize_words)

['The', 'universe', 'is', 'governed', 'by', 'physical', 'laws', 'that', 'can', 'be', 'understood', 'and', 'described', 'mathematically', '.', 'These', 'laws', 'allow', 'us', 'to', 'explain', 'the', 'phenomena', 'we', 'observe', 'and', 'predict', 'future', 'events', '.', 'From', 'the', 'smallest', 'particles', 'to', 'the', 'vast', 'expanse', 'of', 'galaxies', ',', 'the', 'universe', 'operates', 'under', 'principles', 'that', 'reveal', 'its', 'fundamental', 'nature.One', 'of', 'the', 'most', 'profound', 'discoveries', 'in', 'modern', 'physics', 'is', 'the', 'concept', 'of', 'black', 'holes', '.', 'Black', 'holes', 'are', 'regions', 'of', 'spacetime', 'where', 'gravity', 'is', 'so', 'strong', 'that', 'nothing', ',', 'not', 'even', 'light', ',', 'can', 'escape', 'from', 'them', '.', 'They', 'challenge', 'our', 'understanding', 'of', 'time', 'and', 'space', ',', 'leading', 'to', 'questions', 'about', 'the', 'very', 'fabric', 'of', 'reality', '.', 'Understanding', 'black', 'holes', 'and', 't

In [ ]:
word_tokens = text.split()
word_tokens

['The',
 'universe',
 'is',
 'governed',
 'by',
 'physical',
 'laws',
 'that',
 'can',
 'be',
 'understood',
 'and',
 'described',
 'mathematically.',
 'These',
 'laws',
 'allow',
 'us',
 'to',
 'explain',
 'the',
 'phenomena',
 'we',
 'observe',
 'and',
 'predict',
 'future',
 'events.',
 'From',
 'the',
 'smallest',
 'particles',
 'to',
 'the',
 'vast',
 'expanse',
 'of',
 'galaxies,',
 'the',
 'universe',
 'operates',
 'under',
 'principles',
 'that',
 'reveal',
 'its',
 'fundamental',
 'nature.One',
 'of',
 'the',
 'most',
 'profound',
 'discoveries',
 'in',
 'modern',
 'physics',
 'is',
 'the',
 'concept',
 'of',
 'black',
 'holes.',
 'Black',
 'holes',
 'are',
 'regions',
 'of',
 'spacetime',
 'where',
 'gravity',
 'is',
 'so',
 'strong',
 'that',
 'nothing,',
 'not',
 'even',
 'light,',
 'can',
 'escape',
 'from',
 'them.',
 'They',
 'challenge',
 'our',
 'understanding',
 'of',
 'time',
 'and',
 'space,',
 'leading',
 'to',
 'questions',
 'about',
 'the',
 'very',
 'fabric',
 '

In [ ]:
filtered_text = [word for word in word_tokens if word not in stop_words]
print("Filtered Text:", filtered_text)

Filtered Text: ['The', 'universe', 'governed', 'physical', 'laws', 'understood', 'described', 'mathematically.', 'These', 'laws', 'allow', 'us', 'explain', 'phenomena', 'observe', 'predict', 'future', 'events.', 'From', 'smallest', 'particles', 'vast', 'expanse', 'galaxies,', 'universe', 'operates', 'principles', 'reveal', 'fundamental', 'nature.One', 'profound', 'discoveries', 'modern', 'physics', 'concept', 'black', 'holes.', 'Black', 'holes', 'regions', 'spacetime', 'gravity', 'strong', 'nothing,', 'even', 'light,', 'escape', 'them.', 'They', 'challenge', 'understanding', 'time', 'space,', 'leading', 'questions', 'fabric', 'reality.', 'Understanding', 'black', 'holes', 'role', 'cosmos', 'could', 'provide', 'insights', 'origins', 'universe', 'laws', 'govern', 'it.', 'Source:', 'https://www.fisica.net/relatividade/stephen_hawking_a_brief_history_of_time.pdf']


In [ ]:
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

In [ ]:
remove_urls(text)

'The universe is governed by physical laws that can be understood and described mathematically. These laws allow us to explain the phenomena we observe and predict future events. From the smallest particles to the vast expanse of galaxies, the universe operates under principles that reveal its fundamental nature.One of the most profound discoveries in modern physics is the concept of black holes. Black holes are regions of spacetime where gravity is so strong that nothing, not even light, can escape from them. They challenge our understanding of time and space, leading to questions about the very fabric of reality. Understanding black holes and their role in the cosmos could provide insights into the origins of the universe and the laws that govern it. Source: '

In [ ]:
text2 = """
<h1>Myself an enthusiastic coder</h1>
<p>The bootcamp is fun</p>
<a href="https://example.com"></a>
"""

In [ ]:
html_tags_pattern = r'<.*?>'
text_without_html_tags = re.sub(html_tags_pattern, '', text2)
text_without_html_tags

'\nMyself an enthusiastic coder\nThe bootcamp is fun\n\n'

In [ ]:
from nltk.stem.porter import PorterStemmer

In [ ]:
stemmer = PorterStemmer()

In [ ]:
def stem_words(text):
    word_tokens = text.split()
    stems = [stemmer.stem(word) for word in word_tokens]
    return stems

In [ ]:
stem_words(text)

['the',
 'univers',
 'is',
 'govern',
 'by',
 'physic',
 'law',
 'that',
 'can',
 'be',
 'understood',
 'and',
 'describ',
 'mathematically.',
 'these',
 'law',
 'allow',
 'us',
 'to',
 'explain',
 'the',
 'phenomena',
 'we',
 'observ',
 'and',
 'predict',
 'futur',
 'events.',
 'from',
 'the',
 'smallest',
 'particl',
 'to',
 'the',
 'vast',
 'expans',
 'of',
 'galaxies,',
 'the',
 'univers',
 'oper',
 'under',
 'principl',
 'that',
 'reveal',
 'it',
 'fundament',
 'nature.on',
 'of',
 'the',
 'most',
 'profound',
 'discoveri',
 'in',
 'modern',
 'physic',
 'is',
 'the',
 'concept',
 'of',
 'black',
 'holes.',
 'black',
 'hole',
 'are',
 'region',
 'of',
 'spacetim',
 'where',
 'graviti',
 'is',
 'so',
 'strong',
 'that',
 'nothing,',
 'not',
 'even',
 'light,',
 'can',
 'escap',
 'from',
 'them.',
 'they',
 'challeng',
 'our',
 'understand',
 'of',
 'time',
 'and',
 'space,',
 'lead',
 'to',
 'question',
 'about',
 'the',
 'veri',
 'fabric',
 'of',
 'reality.',
 'understand',
 'black

In [ ]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package wordnet to C:\Users\Guru Jahnavi
[nltk_data]     Madana\AppData\Roaming\nltk_data...


In [ ]:
lemmatizer = WordNetLemmatizer()

In [ ]:
def lemmatize_word(text):
    word_tokens = text.split()
    lemmas = [lemmatizer.lemmatize(word, pos ='v') for word in word_tokens]
    return lemmas

In [ ]:
lemmatize_word(text)

['The',
 'universe',
 'be',
 'govern',
 'by',
 'physical',
 'laws',
 'that',
 'can',
 'be',
 'understand',
 'and',
 'describe',
 'mathematically.',
 'These',
 'laws',
 'allow',
 'us',
 'to',
 'explain',
 'the',
 'phenomena',
 'we',
 'observe',
 'and',
 'predict',
 'future',
 'events.',
 'From',
 'the',
 'smallest',
 'particles',
 'to',
 'the',
 'vast',
 'expanse',
 'of',
 'galaxies,',
 'the',
 'universe',
 'operate',
 'under',
 'principles',
 'that',
 'reveal',
 'its',
 'fundamental',
 'nature.One',
 'of',
 'the',
 'most',
 'profound',
 'discoveries',
 'in',
 'modern',
 'physics',
 'be',
 'the',
 'concept',
 'of',
 'black',
 'holes.',
 'Black',
 'hole',
 'be',
 'regions',
 'of',
 'spacetime',
 'where',
 'gravity',
 'be',
 'so',
 'strong',
 'that',
 'nothing,',
 'not',
 'even',
 'light,',
 'can',
 'escape',
 'from',
 'them.',
 'They',
 'challenge',
 'our',
 'understand',
 'of',
 'time',
 'and',
 'space,',
 'lead',
 'to',
 'question',
 'about',
 'the',
 'very',
 'fabric',
 'of',
 'realit

In [ ]:
tokens = word_tokenize(text)
print(tokens)

['The', 'universe', 'is', 'governed', 'by', 'physical', 'laws', 'that', 'can', 'be', 'understood', 'and', 'described', 'mathematically', '.', 'These', 'laws', 'allow', 'us', 'to', 'explain', 'the', 'phenomena', 'we', 'observe', 'and', 'predict', 'future', 'events', '.', 'From', 'the', 'smallest', 'particles', 'to', 'the', 'vast', 'expanse', 'of', 'galaxies', ',', 'the', 'universe', 'operates', 'under', 'principles', 'that', 'reveal', 'its', 'fundamental', 'nature.One', 'of', 'the', 'most', 'profound', 'discoveries', 'in', 'modern', 'physics', 'is', 'the', 'concept', 'of', 'black', 'holes', '.', 'Black', 'holes', 'are', 'regions', 'of', 'spacetime', 'where', 'gravity', 'is', 'so', 'strong', 'that', 'nothing', ',', 'not', 'even', 'light', ',', 'can', 'escape', 'from', 'them', '.', 'They', 'challenge', 'our', 'understanding', 'of', 'time', 'and', 'space', ',', 'leading', 'to', 'questions', 'about', 'the', 'very', 'fabric', 'of', 'reality', '.', 'Understanding', 'black', 'holes', 'and', 't

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
feature_names = vectorizer.get_feature_names_out()
X_array = X.toarray()

In [ ]:
print("Unique Word List: \n", feature_names)
print("Bag of Words Matrix: \n", X_array)

Unique Word List: 
 ['allow' 'black' 'challenge' 'concept' 'cosmos' 'could' 'described'
 'discovery' 'escape' 'even' 'events' 'expanse' 'explain' 'fabric' 'from'
 'fundamental' 'future' 'galaxies' 'govern' 'governed' 'gravity' 'hole'
 'holes'
 'httpswwwfisicanetrelatividadestephen_hawking_a_brief_history_of_timepdf'
 'insight' 'it' 'law' 'leading' 'light' 'mathematically' 'modern'
 'natureone' 'nothing' 'observe' 'operates' 'origin' 'particle'
 'phenomenon' 'physic' 'physical' 'predict' 'principle' 'profound'
 'provide' 'question' 'reality' 'region' 'reveal' 'role' 'smallest'
 'source' 'space' 'spacetime' 'strong' 'the' 'them' 'these' 'they' 'time'
 'understanding' 'understood' 'universe' 'vast']
Bag of Words Matrix: 
 [[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
  0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 1

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(data=X_array, columns=feature_names, index=corpus)
(df)

allow  black  challenge  \
the universe governed physical law understood d...      0      0          0   
these law allow u explain phenomenon observe pr...      1      0          0   
from smallest particle vast expanse galaxies un...      0      1          0   
black hole region spacetime gravity strong noth...      0      1          0   
they challenge understanding time space leading...      0      0          1   
understanding black hole role cosmos could prov...      0      1          0   
source httpswwwfisicanetrelatividadestephen_haw...      0      0          0   

                                                    concept  cosmos  could  \
the universe governed physical law understood d...        0       0      0   
these law allow u explain phenomenon observe pr...        0       0      0   
from smallest particle vast expanse galaxies un...        1       0      0   
black hole region spacetime gravity strong noth...        0       0      0   
they challenge understanding time space leading...        0       0      0   
understanding black hole role cosmos could prov...        0       1      1   
source httpswwwfisicanetrelatividadestephen_haw...        0       0      0   

                                                    described  discovery  \
the universe governed physical law understood d...          1          0   
these law allow u explain phenomenon observe pr...          0          0   
from smallest particle vast expanse galaxies un...          0          1   
black hole region spacetime gravity strong noth...          0          0   
they challenge understanding time space leading...          0          0   
understanding black hole role cosmos could prov...          0          0   
source httpswwwfisicanetrelatividadestephen_haw...          0          0   

                                                    escape  even  ...  strong  \
the universe governed physical law understood d...       0     0  ...       0   
these law allow u explain phenomenon observe pr...       0     0  ...       0   
from smallest particle vast expanse galaxies un...       0     0  ...       0   
black hole region spacetime gravity strong noth...       1     1  ...       1   
they challenge understanding time space leading...       0     0  ...       0   
understanding black hole role cosmos could prov...       0     0  ...       0   
source httpswwwfisicanetrelatividadestephen_haw...       0     0  ...       0   

                                                    the  them  these  they  \
the universe governed physical law understood d...    1     0      0     0   
these law allow u explain phenomenon observe pr...    0     0      1     0   
from smallest particle vast expanse galaxies un...    0     0      0     0   
black hole region spacetime gravity strong noth...    0     1      0     0   
they challenge understanding time space leading...    0     0      0     1   
understanding black hole role cosmos could prov...    0     0      0     0   
source httpswwwfisicanetrelatividadestephen_haw...    0     0      0     0   

                                                    time  understanding  \
the universe governed physical law understood d...     0              0   
these law allow u explain phenomenon observe pr...     0              0   
from smallest particle vast expanse galaxies un...     0              0   
black hole region spacetime gravity strong noth...     0              0   
they challenge understanding time space leading...     1              1   
understanding black hole role cosmos could prov...     0              1   
source httpswwwfisicanetrelatividadestephen_haw...     0              0   

                                                    understood  universe  vast  
the universe governed physical law understood d...           1         1     0  
these law allow u explain phenomenon observe pr...           0         0     0  
from smallest particle vast expanse galaxies un...           0     

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)
terms = tfidf_vectorizer.get_feature_names_out()
df = pd.DataFrame(tfidf_matrix.toarray(), columns=terms)
(df)

allow     black  challenge   concept    cosmos     could  described  \
0  0.000000  0.000000   0.000000  0.000000  0.000000  0.000000   0.377779   
1  0.342928  0.000000   0.000000  0.000000  0.000000  0.000000   0.000000   
2  0.000000  0.167206   0.000000  0.235657  0.000000  0.000000   0.000000   
3  0.000000  0.222244   0.000000  0.000000  0.000000  0.000000   0.000000   
4  0.000000  0.000000   0.339245  0.000000  0.000000  0.000000   0.000000   
5  0.000000  0.215025   0.000000  0.000000  0.303053  0.303053   0.000000   
6  0.000000  0.000000   0.000000  0.000000  0.000000  0.000000   0.000000   

   discovery    escape      even  ...    strong       the      them     these  \
0   0.000000  0.000000  0.000000  ...  0.000000  0.377779  0.000000  0.000000   
1   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.342928   
2   0.235657  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3   0.000000  0.313228  0.313228  ...  0.313228  0.000000  0.313228  0.000000   
4   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
5   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
6   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   

       they      time  understanding  understood  universe      vast  
0  0.000000  0.000000       0.000000    0.377779  0.268046  0.000000  
1  0.000000  0.000000       0.000000    0.000000  0.000000  0.000000  
2  0.000000  0.000000       0.000000    0.000000  0.167206  0.235657  
3  0.000000  0.000000       0.000000    0.000000  0.000000  0.000000  
4  0.339245  0.339245       0.281603    0.000000  0.000000  0.000000  
5  0.000000  0.000000       0.251560    0.000000  0.215025  0.000000  
6  0.000000  0.000000       0.000000    0.000000  0.000000  0.000000  

[7 rows x 63 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
import numpy as np

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\Guru Jahnavi
[nltk_data]     Madana\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [ ]:
tokenized_text = [nltk.word_tokenize(sentence.lower()) for sentence in text]

In [ ]:
all_words = [word for sentence in tokenized_text for word in sentence]

In [ ]:
vocab = sorted(set(all_words))

In [ ]:
print("Vocabulary:", vocab)

Vocabulary: [',', '.', '/', ':', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y']


In [ ]:
word_array = np.array(all_words).reshape(-1, 1)

In [ ]:
one_hot_encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded = one_hot_encoder.fit_transform(word_array)

In [ ]:
print("One-hot encoded matrix:\n", one_hot_encoded)

One-hot encoded matrix:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
