<a href="https://colab.research.google.com/github/GJ-007-sage/deep-learning/blob/main/corpus2-biodiversity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import re

In [49]:
text = "Biodiversity refers to the variety of life on Earth, encompassing all living organisms, their genetic differences, and the ecosystems they form. It is crucial for maintaining ecosystem services, which include air and water purification, pollination of plants, and climate regulation.The loss of biodiversity poses a significant threat to the health of our planet. Activities such as deforestation, pollution, and climate change are driving many species to extinction. Protecting biodiversity is essential not only for the survival of individual species but also for human well-being, as it supports food security and provides resources for medicine and economic development.. Source: https://www.worldwildlife.org/pages/what-is-biodiversity"

In [50]:
lowercased_text = text.lower()

lowercased_text

'biodiversity refers to the variety of life on earth, encompassing all living organisms, their genetic differences, and the ecosystems they form. it is crucial for maintaining ecosystem services, which include air and water purification, pollination of plants, and climate regulation.the loss of biodiversity poses a significant threat to the health of our planet. activities such as deforestation, pollution, and climate change are driving many species to extinction. protecting biodiversity is essential not only for the survival of individual species but also for human well-being, as it supports food security and provides resources for medicine and economic development.. source: https://www.worldwildlife.org/pages/what-is-biodiversity'

In [51]:
punctuation_pattern = r'[^\w\s]'
text_cleaned = re.sub(punctuation_pattern, '', text)
text_cleaned

'Biodiversity refers to the variety of life on Earth encompassing all living organisms their genetic differences and the ecosystems they form It is crucial for maintaining ecosystem services which include air and water purification pollination of plants and climate regulationThe loss of biodiversity poses a significant threat to the health of our planet Activities such as deforestation pollution and climate change are driving many species to extinction Protecting biodiversity is essential not only for the survival of individual species but also for human wellbeing as it supports food security and provides resources for medicine and economic development Source httpswwwworldwildlifeorgpageswhatisbiodiversity'

In [52]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [53]:
stop_words = set(stopwords.words('english'))

In [54]:
print(stop_words)

{'did', "don't", 'before', 'we', 'these', 'there', 'such', 'ours', 'who', 'when', 'under', 'm', 'was', 'by', 'above', "she's", 'until', 'which', 'you', 'about', "you'd", 'too', 'having', 'does', 'had', 'other', "you've", "doesn't", 'doing', 'shan', 'been', 'am', 'is', 'being', 'weren', "shouldn't", 'very', 'whom', 'if', 'i', 'my', 'hers', 'itself', 'both', 'o', 'few', 'over', 'why', 'as', 'against', 'she', "that'll", 'than', 'off', 'own', 'some', 'here', "hasn't", 'not', 'll', 're', "haven't", 'wasn', "won't", 'hasn', "you're", 'isn', 'were', 'y', 'doesn', 'then', 'their', 'after', 'at', 'ma', "you'll", 'are', 'should', 'where', 'has', 'have', 'any', "needn't", "isn't", 've', 'all', 'during', 'its', 'because', 'further', 'ain', 'myself', 'most', 'mustn', 'theirs', 'those', 'himself', 'how', 'do', 'shouldn', 'down', 'ourselves', 'don', "mustn't", "wouldn't", "mightn't", 'but', 'only', 'now', 'themselves', 'into', 'in', 'once', "wasn't", 'between', 'yours', 'and', 'herself', "weren't", '

In [55]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize,sent_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [56]:
tokenize_words = word_tokenize(text)

In [57]:
print(tokenize_words)

['Biodiversity', 'refers', 'to', 'the', 'variety', 'of', 'life', 'on', 'Earth', ',', 'encompassing', 'all', 'living', 'organisms', ',', 'their', 'genetic', 'differences', ',', 'and', 'the', 'ecosystems', 'they', 'form', '.', 'It', 'is', 'crucial', 'for', 'maintaining', 'ecosystem', 'services', ',', 'which', 'include', 'air', 'and', 'water', 'purification', ',', 'pollination', 'of', 'plants', ',', 'and', 'climate', 'regulation.The', 'loss', 'of', 'biodiversity', 'poses', 'a', 'significant', 'threat', 'to', 'the', 'health', 'of', 'our', 'planet', '.', 'Activities', 'such', 'as', 'deforestation', ',', 'pollution', ',', 'and', 'climate', 'change', 'are', 'driving', 'many', 'species', 'to', 'extinction', '.', 'Protecting', 'biodiversity', 'is', 'essential', 'not', 'only', 'for', 'the', 'survival', 'of', 'individual', 'species', 'but', 'also', 'for', 'human', 'well-being', ',', 'as', 'it', 'supports', 'food', 'security', 'and', 'provides', 'resources', 'for', 'medicine', 'and', 'economic', '

In [58]:
word_tokens = text.split()
word_tokens

['Biodiversity',
 'refers',
 'to',
 'the',
 'variety',
 'of',
 'life',
 'on',
 'Earth,',
 'encompassing',
 'all',
 'living',
 'organisms,',
 'their',
 'genetic',
 'differences,',
 'and',
 'the',
 'ecosystems',
 'they',
 'form.',
 'It',
 'is',
 'crucial',
 'for',
 'maintaining',
 'ecosystem',
 'services,',
 'which',
 'include',
 'air',
 'and',
 'water',
 'purification,',
 'pollination',
 'of',
 'plants,',
 'and',
 'climate',
 'regulation.The',
 'loss',
 'of',
 'biodiversity',
 'poses',
 'a',
 'significant',
 'threat',
 'to',
 'the',
 'health',
 'of',
 'our',
 'planet.',
 'Activities',
 'such',
 'as',
 'deforestation,',
 'pollution,',
 'and',
 'climate',
 'change',
 'are',
 'driving',
 'many',
 'species',
 'to',
 'extinction.',
 'Protecting',
 'biodiversity',
 'is',
 'essential',
 'not',
 'only',
 'for',
 'the',
 'survival',
 'of',
 'individual',
 'species',
 'but',
 'also',
 'for',
 'human',
 'well-being,',
 'as',
 'it',
 'supports',
 'food',
 'security',
 'and',
 'provides',
 'resource

In [59]:
filtered_text = [word for word in word_tokens if word not in stop_words]
print("Filtered Text:", filtered_text)

Filtered Text: ['Biodiversity', 'refers', 'variety', 'life', 'Earth,', 'encompassing', 'living', 'organisms,', 'genetic', 'differences,', 'ecosystems', 'form.', 'It', 'crucial', 'maintaining', 'ecosystem', 'services,', 'include', 'air', 'water', 'purification,', 'pollination', 'plants,', 'climate', 'regulation.The', 'loss', 'biodiversity', 'poses', 'significant', 'threat', 'health', 'planet.', 'Activities', 'deforestation,', 'pollution,', 'climate', 'change', 'driving', 'many', 'species', 'extinction.', 'Protecting', 'biodiversity', 'essential', 'survival', 'individual', 'species', 'also', 'human', 'well-being,', 'supports', 'food', 'security', 'provides', 'resources', 'medicine', 'economic', 'development..', 'Source:', 'https://www.worldwildlife.org/pages/what-is-biodiversity']


In [60]:
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

In [61]:
remove_urls(text)

'Biodiversity refers to the variety of life on Earth, encompassing all living organisms, their genetic differences, and the ecosystems they form. It is crucial for maintaining ecosystem services, which include air and water purification, pollination of plants, and climate regulation.The loss of biodiversity poses a significant threat to the health of our planet. Activities such as deforestation, pollution, and climate change are driving many species to extinction. Protecting biodiversity is essential not only for the survival of individual species but also for human well-being, as it supports food security and provides resources for medicine and economic development.. Source: '

5. stemming


In [62]:
from nltk.stem.porter import PorterStemmer

In [63]:
stemmer = PorterStemmer()

In [64]:
def stem_words(text):
    word_tokens = text.split()
    stems = [stemmer.stem(word) for word in word_tokens]
    return stems

In [65]:
stem_words(text)

['biodivers',
 'refer',
 'to',
 'the',
 'varieti',
 'of',
 'life',
 'on',
 'earth,',
 'encompass',
 'all',
 'live',
 'organisms,',
 'their',
 'genet',
 'differences,',
 'and',
 'the',
 'ecosystem',
 'they',
 'form.',
 'it',
 'is',
 'crucial',
 'for',
 'maintain',
 'ecosystem',
 'services,',
 'which',
 'includ',
 'air',
 'and',
 'water',
 'purification,',
 'pollin',
 'of',
 'plants,',
 'and',
 'climat',
 'regulation.th',
 'loss',
 'of',
 'biodivers',
 'pose',
 'a',
 'signific',
 'threat',
 'to',
 'the',
 'health',
 'of',
 'our',
 'planet.',
 'activ',
 'such',
 'as',
 'deforestation,',
 'pollution,',
 'and',
 'climat',
 'chang',
 'are',
 'drive',
 'mani',
 'speci',
 'to',
 'extinction.',
 'protect',
 'biodivers',
 'is',
 'essenti',
 'not',
 'onli',
 'for',
 'the',
 'surviv',
 'of',
 'individu',
 'speci',
 'but',
 'also',
 'for',
 'human',
 'well-being,',
 'as',
 'it',
 'support',
 'food',
 'secur',
 'and',
 'provid',
 'resourc',
 'for',
 'medicin',
 'and',
 'econom',
 'development..',
 '

In [66]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [67]:
lemmatizer = WordNetLemmatizer()

In [68]:
def lemmatize_word(text):
    word_tokens = text.split()
    lemmas = [lemmatizer.lemmatize(word, pos ='v') for word in word_tokens]
    return lemmas

In [69]:
lemmatize_word(text)

['Biodiversity',
 'refer',
 'to',
 'the',
 'variety',
 'of',
 'life',
 'on',
 'Earth,',
 'encompass',
 'all',
 'live',
 'organisms,',
 'their',
 'genetic',
 'differences,',
 'and',
 'the',
 'ecosystems',
 'they',
 'form.',
 'It',
 'be',
 'crucial',
 'for',
 'maintain',
 'ecosystem',
 'services,',
 'which',
 'include',
 'air',
 'and',
 'water',
 'purification,',
 'pollination',
 'of',
 'plants,',
 'and',
 'climate',
 'regulation.The',
 'loss',
 'of',
 'biodiversity',
 'pose',
 'a',
 'significant',
 'threat',
 'to',
 'the',
 'health',
 'of',
 'our',
 'planet.',
 'Activities',
 'such',
 'as',
 'deforestation,',
 'pollution,',
 'and',
 'climate',
 'change',
 'be',
 'drive',
 'many',
 'species',
 'to',
 'extinction.',
 'Protecting',
 'biodiversity',
 'be',
 'essential',
 'not',
 'only',
 'for',
 'the',
 'survival',
 'of',
 'individual',
 'species',
 'but',
 'also',
 'for',
 'human',
 'well-being,',
 'as',
 'it',
 'support',
 'food',
 'security',
 'and',
 'provide',
 'resources',
 'for',
 'm

In [70]:
tokens = word_tokenize(text)
print(tokens)

['Biodiversity', 'refers', 'to', 'the', 'variety', 'of', 'life', 'on', 'Earth', ',', 'encompassing', 'all', 'living', 'organisms', ',', 'their', 'genetic', 'differences', ',', 'and', 'the', 'ecosystems', 'they', 'form', '.', 'It', 'is', 'crucial', 'for', 'maintaining', 'ecosystem', 'services', ',', 'which', 'include', 'air', 'and', 'water', 'purification', ',', 'pollination', 'of', 'plants', ',', 'and', 'climate', 'regulation.The', 'loss', 'of', 'biodiversity', 'poses', 'a', 'significant', 'threat', 'to', 'the', 'health', 'of', 'our', 'planet', '.', 'Activities', 'such', 'as', 'deforestation', ',', 'pollution', ',', 'and', 'climate', 'change', 'are', 'driving', 'many', 'species', 'to', 'extinction', '.', 'Protecting', 'biodiversity', 'is', 'essential', 'not', 'only', 'for', 'the', 'survival', 'of', 'individual', 'species', 'but', 'also', 'for', 'human', 'well-being', ',', 'as', 'it', 'supports', 'food', 'security', 'and', 'provides', 'resources', 'for', 'medicine', 'and', 'economic', '

In [71]:
from sklearn.feature_extraction.text import CountVectorizer

In [72]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(tokens)
feature_names = vectorizer.get_feature_names_out()
X_array = X.toarray()

In [73]:
print("Unique Word List: \n", feature_names)
print("Bag of Words Matrix: \n", X_array)

Unique Word List: 
 ['activities' 'air' 'all' 'also' 'and' 'are' 'as' 'being' 'biodiversity'
 'but' 'change' 'climate' 'crucial' 'deforestation' 'development'
 'differences' 'driving' 'earth' 'economic' 'ecosystem' 'ecosystems'
 'encompassing' 'essential' 'extinction' 'food' 'for' 'form' 'genetic'
 'health' 'https' 'human' 'include' 'individual' 'is' 'it' 'life' 'living'
 'loss' 'maintaining' 'many' 'medicine' 'not' 'of' 'on' 'only' 'org'
 'organisms' 'our' 'pages' 'planet' 'plants' 'pollination' 'pollution'
 'poses' 'protecting' 'provides' 'purification' 'refers' 'regulation'
 'resources' 'security' 'services' 'significant' 'source' 'species' 'such'
 'supports' 'survival' 'the' 'their' 'they' 'threat' 'to' 'variety'
 'water' 'well' 'what' 'which' 'worldwildlife' 'www']
Bag of Words Matrix: 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 1]]


In [74]:
import pandas as pd

In [75]:
df = pd.DataFrame(data=X_array, columns=feature_names, index=tokens)
(df)

activities  air  all  \
Biodiversity                                                 0    0    0   
refers                                                       0    0    0   
to                                                           0    0    0   
the                                                          0    0    0   
variety                                                      0    0    0   
...                                                        ...  ...  ...   
Source                                                       0    0    0   
:                                                            0    0    0   
https                                                        0    0    0   
:                                                            0    0    0   
//www.worldwildlife.org/pages/what-is-biodiversity           0    0    0   

                                                    also  and  are  as  being  \
Biodiversity                                           0    0    0   0      0   
refers                                                 0    0    0   0      0   
to                                                     0    0    0   0      0   
the                                                    0    0    0   0      0   
variety                                                0    0    0   0      0   
...                                                  ...  ...  ...  ..    ...   
Source                                                 0    0    0   0      0   
:                                                      0    0    0   0      0   
https                                                  0    0    0   0      0   
:                                                      0    0    0   0      0   
//www.worldwildlife.org/pages/what-is-biodiversity     0    0    0   0      0   

                                                    biodiversity  but  ...  \
Biodiversity                                                   1    0  ...   
refers                                                         0    0  ...   
to                                                             0    0  ...   
the                                                            0    0  ...   
variety                                                        0    0  ...   
...                                                          ...  ...  ...   
Source                                                         0    0  ...   
:                                                              0    0  ...   
https                                                          0    0  ...   
:                                                              0    0  ...   
//www.worldwildlife.org/pages/what-is-biodiversity             1    0  ...   

                                                    they  threat  to  variety  \
Biodiversity                                           0       0   0        0   
refers                                                 0       0   0        0   
to                                                     0       0   1        0   
the                                                    0       0   0        0   
variety                                                0       0   0        1   
...                                                  ...     ...  ..      ...   
Source                                                 0       0   0        0   
:                                                      0       0   0        0   
https                                                  0       0   0        0   
:                                                      0       0   0        0   
//www.worldwildlife.org/pages/what-is-biodiversity     0       0   0        0   

                                                    water  well  what  which  \
Biodiversity                                            0     0     0      0   
refers                                                  0     0     0      0   
to              

In [76]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [77]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(tokens)
terms = tfidf_vectorizer.get_feature_names_out()
df = pd.DataFrame(tfidf_matrix.toarray(), columns=terms)
(df)

activities  air  all  also  and  are   as  being  biodiversity  but  ...  \
0           0.0  0.0  0.0   0.0  0.0  0.0  0.0    0.0       1.00000  0.0  ...   
1           0.0  0.0  0.0   0.0  0.0  0.0  0.0    0.0       0.00000  0.0  ...   
2           0.0  0.0  0.0   0.0  0.0  0.0  0.0    0.0       0.00000  0.0  ...   
3           0.0  0.0  0.0   0.0  0.0  0.0  0.0    0.0       0.00000  0.0  ...   
4           0.0  0.0  0.0   0.0  0.0  0.0  0.0    0.0       0.00000  0.0  ...   
..          ...  ...  ...   ...  ...  ...  ...    ...           ...  ...  ...   
110         0.0  0.0  0.0   0.0  0.0  0.0  0.0    0.0       0.00000  0.0  ...   
111         0.0  0.0  0.0   0.0  0.0  0.0  0.0    0.0       0.00000  0.0  ...   
112         0.0  0.0  0.0   0.0  0.0  0.0  0.0    0.0       0.00000  0.0  ...   
113         0.0  0.0  0.0   0.0  0.0  0.0  0.0    0.0       0.00000  0.0  ...   
114         0.0  0.0  0.0   0.0  0.0  0.0  0.0    0.0       0.32332  0.0  ...   

     they  threat   to  variety  water  well      what  which  worldwildlife  \
0     0.0     0.0  0.0      0.0    0.0   0.0  0.000000    0.0       0.000000   
1     0.0     0.0  0.0      0.0    0.0   0.0  0.000000    0.0       0.000000   
2     0.0     0.0  1.0      0.0    0.0   0.0  0.000000    0.0       0.000000   
3     0.0     0.0  0.0      0.0    0.0   0.0  0.000000    0.0       0.000000   
4     0.0     0.0  0.0      1.0    0.0   0.0  0.000000    0.0       0.000000   
..    ...     ...  ...      ...    ...   ...       ...    ...            ...   
110   0.0     0.0  0.0      0.0    0.0   0.0  0.000000    0.0       0.000000   
111   0.0     0.0  0.0      0.0    0.0   0.0  0.000000    0.0       0.000000   
112   0.0     0.0  0.0      0.0    0.0   0.0  0.000000    0.0       0.000000   
113   0.0     0.0  0.0      0.0    0.0   0.0  0.000000    0.0       0.000000   
114   0.0     0.0  0.0      0.0    0.0   0.0  0.394808    0.0       0.394808   

          www  
0    0.000000  
1    0.000000  
2    0.000000  
3    0.000000  
4    0.000000  
..        ...  
110  0.000000  
111  0.000000  
112  0.000000  
113  0.000000  
114  0.394808  

[115 rows x 80 columns]

In [78]:
from sklearn.preprocessing import OneHotEncoder

In [79]:
import numpy as np

In [80]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [81]:
tokenized_text = [nltk.word_tokenize(sentence.lower()) for sentence in text]

In [82]:
all_words = [word for sentence in tokenized_text for word in sentence]

In [83]:
vocab = sorted(set(all_words))

In [84]:
print("Vocabulary:", vocab)

Vocabulary: [',', '-', '.', '/', ':', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y']


In [85]:
word_array = np.array(all_words).reshape(-1, 1)

In [86]:
one_hot_encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded = one_hot_encoder.fit_transform(word_array)

In [87]:
print("One-hot encoded matrix:\n", one_hot_encoded)

One-hot encoded matrix:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
